-- Create the table for Dietary Reference Intakes (RDAs)
CREATE TABLE IF NOT EXISTS public.dietary_reference_intakes (
    id bigint generated by default as identity primary key,
    nutrient text not null,
    min_age integer not null,
    max_age integer not null,
    gender text not null check (gender in ('male', 'female', 'both')),
    value numeric not null,
    unit text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.dietary_reference_intakes ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access on dietary_reference_intakes"
ON public.dietary_reference_intakes FOR SELECT
TO anon
USING (true);

-- Functions to clear existing data before seeding (optional, for idempotency)
TRUNCATE TABLE public.dietary_reference_intakes;

-- SEED DATA based on DRI guidelines

-- TODDLERS (1-3 years)
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 1, 3, 'both', 2000, 'mg'),
('Magnesium', 1, 3, 'both', 80, 'mg'),
('Calcium', 1, 3, 'both', 700, 'mg'),
('Phosphorus', 1, 3, 'both', 460, 'mg'),
('Sodium', 1, 3, 'both', 800, 'mg'),
('Iron', 1, 3, 'both', 7, 'mg'),
('Zinc', 1, 3, 'both', 3, 'mg'),
('Selenium', 1, 3, 'both', 20, 'µg'),
('Copper', 1, 3, 'both', 0.34, 'mg'),
('Manganese', 1, 3, 'both', 1.2, 'mg'),
('Vitamin A', 1, 3, 'both', 300, 'µg'),
('Vitamin C', 1, 3, 'both', 15, 'mg'),
('Vitamin D', 1, 3, 'both', 600, 'IU'),
('Vitamin E', 1, 3, 'both', 6, 'mg'),
('Vitamin K', 1, 3, 'both', 30, 'µg'),
('B1 (Thiamine)', 1, 3, 'both', 0.5, 'mg'),
('B2 (Riboflavin)', 1, 3, 'both', 0.5, 'mg'),
('B3 (Niacin)', 1, 3, 'both', 6, 'mg'),
('B5 (Pantothenic Acid)', 1, 3, 'both', 2, 'mg'),
('B6 (Pyridoxine)', 1, 3, 'both', 0.5, 'mg'),
('B7 (Biotin)', 1, 3, 'both', 8, 'µg'),
('B9 (Folate)', 1, 3, 'both', 150, 'µg'),
('B12 (Cobalamin)', 1, 3, 'both', 0.9, 'µg'),
('Choline', 1, 3, 'both', 200, 'mg'),
('Fiber', 1, 3, 'both', 19, 'g');

-- CHILDREN (4-8 years)
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 4, 8, 'both', 2300, 'mg'),
('Magnesium', 4, 8, 'both', 130, 'mg'),
('Calcium', 4, 8, 'both', 1000, 'mg'),
('Phosphorus', 4, 8, 'both', 500, 'mg'),
('Sodium', 4, 8, 'both', 1000, 'mg'),
('Iron', 4, 8, 'both', 10, 'mg'),
('Zinc', 4, 8, 'both', 5, 'mg'),
('Selenium', 4, 8, 'both', 30, 'µg'),
('Copper', 4, 8, 'both', 0.44, 'mg'),
('Manganese', 4, 8, 'both', 1.5, 'mg'),
('Vitamin A', 4, 8, 'both', 400, 'µg'),
('Vitamin C', 4, 8, 'both', 25, 'mg'),
('Vitamin D', 4, 8, 'both', 600, 'IU'),
('Vitamin E', 4, 8, 'both', 7, 'mg'),
('Vitamin K', 4, 8, 'both', 55, 'µg'),
('B1 (Thiamine)', 4, 8, 'both', 0.6, 'mg'),
('B2 (Riboflavin)', 4, 8, 'both', 0.6, 'mg'),
('B3 (Niacin)', 4, 8, 'both', 8, 'mg'),
('B5 (Pantothenic Acid)', 4, 8, 'both', 3, 'mg'),
('B6 (Pyridoxine)', 4, 8, 'both', 0.6, 'mg'),
('B7 (Biotin)', 4, 8, 'both', 12, 'µg'),
('B9 (Folate)', 4, 8, 'both', 200, 'µg'),
('B12 (Cobalamin)', 4, 8, 'both', 1.2, 'µg'),
('Choline', 4, 8, 'both', 250, 'mg'),
('Fiber', 4, 8, 'both', 25, 'g');

-- CHILDREN (9-13 years)
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 9, 13, 'both', 2500, 'mg'),
('Magnesium', 9, 13, 'both', 240, 'mg'),
('Calcium', 9, 13, 'both', 1300, 'mg'),
('Phosphorus', 9, 13, 'both', 1250, 'mg'),
('Sodium', 9, 13, 'both', 1200, 'mg'),
('Iron', 9, 13, 'both', 8, 'mg'),
('Zinc', 9, 13, 'both', 8, 'mg'),
('Selenium', 9, 13, 'both', 40, 'µg'),
('Copper', 9, 13, 'both', 0.7, 'mg'),
('Manganese', 9, 13, 'both', 1.9, 'mg'),
('Vitamin A', 9, 13, 'both', 600, 'µg'),
('Vitamin C', 9, 13, 'both', 45, 'mg'),
('Vitamin D', 9, 13, 'both', 600, 'IU'),
('Vitamin E', 9, 13, 'both', 11, 'mg'),
('Vitamin K', 9, 13, 'both', 60, 'µg'),
('B1 (Thiamine)', 9, 13, 'both', 0.9, 'mg'),
('B2 (Riboflavin)', 9, 13, 'both', 0.9, 'mg'),
('B3 (Niacin)', 9, 13, 'both', 12, 'mg'),
('B5 (Pantothenic Acid)', 9, 13, 'both', 4, 'mg'),
('B6 (Pyridoxine)', 9, 13, 'both', 1.0, 'mg'),
('B7 (Biotin)', 9, 13, 'both', 20, 'µg'),
('B9 (Folate)', 9, 13, 'both', 300, 'µg'),
('B12 (Cobalamin)', 9, 13, 'both', 1.8, 'µg'),
('Choline', 9, 13, 'both', 375, 'mg'),
('Fiber', 9, 13, 'both', 30, 'g'); -- approx

-- TEENS (14-18 years) - MALE
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 14, 18, 'male', 3000, 'mg'),
('Magnesium', 14, 18, 'male', 410, 'mg'),
('Calcium', 14, 18, 'male', 1300, 'mg'),
('Phosphorus', 14, 18, 'male', 1250, 'mg'),
('Sodium', 14, 18, 'male', 1500, 'mg'),
('Iron', 14, 18, 'male', 11, 'mg'),
('Zinc', 14, 18, 'male', 11, 'mg'),
('Selenium', 14, 18, 'male', 55, 'µg'),
('Copper', 14, 18, 'male', 0.89, 'mg'),
('Manganese', 14, 18, 'male', 2.2, 'mg'),
('Vitamin A', 14, 18, 'male', 900, 'µg'),
('Vitamin C', 14, 18, 'male', 75, 'mg'),
('Vitamin D', 14, 18, 'male', 600, 'IU'),
('Vitamin E', 14, 18, 'male', 15, 'mg'),
('Vitamin K', 14, 18, 'male', 75, 'µg'),
('B1 (Thiamine)', 14, 18, 'male', 1.2, 'mg'),
('B2 (Riboflavin)', 14, 18, 'male', 1.3, 'mg'),
('B3 (Niacin)', 14, 18, 'male', 16, 'mg'),
('B5 (Pantothenic Acid)', 14, 18, 'male', 5, 'mg'),
('B6 (Pyridoxine)', 14, 18, 'male', 1.3, 'mg'),
('B7 (Biotin)', 14, 18, 'male', 25, 'µg'),
('B9 (Folate)', 14, 18, 'male', 400, 'µg'),
('B12 (Cobalamin)', 14, 18, 'male', 2.4, 'µg'),
('Choline', 14, 18, 'male', 550, 'mg'),
('Fiber', 14, 18, 'male', 38, 'g');

-- TEENS (14-18 years) - FEMALE
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 14, 18, 'female', 2300, 'mg'),
('Magnesium', 14, 18, 'female', 360, 'mg'),
('Calcium', 14, 18, 'female', 1300, 'mg'),
('Phosphorus', 14, 18, 'female', 1250, 'mg'),
('Sodium', 14, 18, 'female', 1500, 'mg'),
('Iron', 14, 18, 'female', 15, 'mg'),
('Zinc', 14, 18, 'female', 9, 'mg'),
('Selenium', 14, 18, 'female', 55, 'µg'),
('Copper', 14, 18, 'female', 0.89, 'mg'),
('Manganese', 14, 18, 'female', 1.6, 'mg'),
('Vitamin A', 14, 18, 'female', 700, 'µg'),
('Vitamin C', 14, 18, 'female', 65, 'mg'),
('Vitamin D', 14, 18, 'female', 600, 'IU'),
('Vitamin E', 14, 18, 'female', 15, 'mg'),
('Vitamin K', 14, 18, 'female', 75, 'µg'),
('B1 (Thiamine)', 14, 18, 'female', 1.0, 'mg'),
('B2 (Riboflavin)', 14, 18, 'female', 1.0, 'mg'),
('B3 (Niacin)', 14, 18, 'female', 14, 'mg'),
('B5 (Pantothenic Acid)', 14, 18, 'female', 5, 'mg'),
('B6 (Pyridoxine)', 14, 18, 'female', 1.2, 'mg'),
('B7 (Biotin)', 14, 18, 'female', 25, 'µg'),
('B9 (Folate)', 14, 18, 'female', 400, 'µg'),
('B12 (Cobalamin)', 14, 18, 'female', 2.4, 'µg'),
('Choline', 14, 18, 'female', 400, 'mg'),
('Fiber', 14, 18, 'female', 26, 'g');

-- ADULTS (19-50 years) - MALE
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 19, 50, 'male', 3400, 'mg'),
('Magnesium', 19, 50, 'male', 400, 'mg'),
('Calcium', 19, 50, 'male', 1000, 'mg'),
('Phosphorus', 19, 50, 'male', 700, 'mg'),
('Sodium', 19, 50, 'male', 1500, 'mg'),
('Iron', 19, 50, 'male', 8, 'mg'),
('Zinc', 19, 50, 'male', 11, 'mg'),
('Selenium', 19, 50, 'male', 55, 'µg'),
('Copper', 19, 50, 'male', 0.9, 'mg'),
('Manganese', 19, 50, 'male', 2.3, 'mg'),
('Vitamin A', 19, 50, 'male', 900, 'µg'),
('Vitamin C', 19, 50, 'male', 90, 'mg'),
('Vitamin D', 19, 50, 'male', 600, 'IU'),
('Vitamin E', 19, 50, 'male', 15, 'mg'),
('Vitamin K', 19, 50, 'male', 120, 'µg'),
('B1 (Thiamine)', 19, 50, 'male', 1.2, 'mg'),
('B2 (Riboflavin)', 19, 50, 'male', 1.3, 'mg'),
('B3 (Niacin)', 19, 50, 'male', 16, 'mg'),
('B5 (Pantothenic Acid)', 19, 50, 'male', 5, 'mg'),
('B6 (Pyridoxine)', 19, 50, 'male', 1.3, 'mg'),
('B7 (Biotin)', 19, 50, 'male', 30, 'µg'),
('B9 (Folate)', 19, 50, 'male', 400, 'µg'),
('B12 (Cobalamin)', 19, 50, 'male', 2.4, 'µg'),
('Choline', 19, 50, 'male', 550, 'mg'),
('Fiber', 19, 50, 'male', 38, 'g');

-- ADULTS (19-50 years) - FEMALE
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 19, 50, 'female', 2600, 'mg'),
('Magnesium', 19, 50, 'female', 310, 'mg'),
('Calcium', 19, 50, 'female', 1000, 'mg'),
('Phosphorus', 19, 50, 'female', 700, 'mg'),
('Sodium', 19, 50, 'female', 1500, 'mg'),
('Iron', 19, 50, 'female', 18, 'mg'),
('Zinc', 19, 50, 'female', 8, 'mg'),
('Selenium', 19, 50, 'female', 55, 'µg'),
('Copper', 19, 50, 'female', 0.9, 'mg'),
('Manganese', 19, 50, 'female', 1.8, 'mg'),
('Vitamin A', 19, 50, 'female', 700, 'µg'),
('Vitamin C', 19, 50, 'female', 75, 'mg'),
('Vitamin D', 19, 50, 'female', 600, 'IU'),
('Vitamin E', 19, 50, 'female', 15, 'mg'),
('Vitamin K', 19, 50, 'female', 90, 'µg'),
('B1 (Thiamine)', 19, 50, 'female', 1.1, 'mg'),
('B2 (Riboflavin)', 19, 50, 'female', 1.1, 'mg'),
('B3 (Niacin)', 19, 50, 'female', 14, 'mg'),
('B5 (Pantothenic Acid)', 19, 50, 'female', 5, 'mg'),
('B6 (Pyridoxine)', 19, 50, 'female', 1.3, 'mg'),
('B7 (Biotin)', 19, 50, 'female', 30, 'µg'),
('B9 (Folate)', 19, 50, 'female', 400, 'µg'),
('B12 (Cobalamin)', 19, 50, 'female', 2.4, 'µg'),
('Choline', 19, 50, 'female', 425, 'mg'),
('Fiber', 19, 50, 'female', 25, 'g');

-- ADULTS (51+ years) - MALE
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 51, 120, 'male', 3400, 'mg'),
('Magnesium', 51, 120, 'male', 420, 'mg'),
('Calcium', 51, 120, 'male', 1000, 'mg'), -- 1200 for 70+
('Phosphorus', 51, 120, 'male', 700, 'mg'),
('Sodium', 51, 120, 'male', 1500, 'mg'),
('Iron', 51, 120, 'male', 8, 'mg'),
('Zinc', 51, 120, 'male', 11, 'mg'),
('Selenium', 51, 120, 'male', 55, 'µg'),
('Copper', 51, 120, 'male', 0.9, 'mg'),
('Manganese', 51, 120, 'male', 2.3, 'mg'),
('Vitamin A', 51, 120, 'male', 900, 'µg'),
('Vitamin C', 51, 120, 'male', 90, 'mg'),
('Vitamin D', 51, 120, 'male', 600, 'IU'), -- 800 for 70+
('Vitamin E', 51, 120, 'male', 15, 'mg'),
('Vitamin K', 51, 120, 'male', 120, 'µg'),
('B1 (Thiamine)', 51, 120, 'male', 1.2, 'mg'),
('B2 (Riboflavin)', 51, 120, 'male', 1.3, 'mg'),
('B3 (Niacin)', 51, 120, 'male', 16, 'mg'),
('B5 (Pantothenic Acid)', 51, 120, 'male', 5, 'mg'),
('B6 (Pyridoxine)', 51, 120, 'male', 1.7, 'mg'),
('B7 (Biotin)', 51, 120, 'male', 30, 'µg'),
('B9 (Folate)', 51, 120, 'male', 400, 'µg'),
('B12 (Cobalamin)', 51, 120, 'male', 2.4, 'µg'),
('Choline', 51, 120, 'male', 550, 'mg'),
('Fiber', 51, 120, 'male', 30, 'g');

-- ADULTS (51+ years) - FEMALE
INSERT INTO public.dietary_reference_intakes (nutrient, min_age, max_age, gender, value, unit) VALUES
('Potassium', 51, 120, 'female', 2600, 'mg'),
('Magnesium', 51, 120, 'female', 320, 'mg'),
('Calcium', 51, 120, 'female', 1200, 'mg'),
('Phosphorus', 51, 120, 'female', 700, 'mg'),
('Sodium', 51, 120, 'female', 1500, 'mg'),
('Iron', 51, 120, 'female', 8, 'mg'),
('Zinc', 51, 120, 'female', 8, 'mg'),
('Selenium', 51, 120, 'female', 55, 'µg'),
('Copper', 51, 120, 'female', 0.9, 'mg'),
('Manganese', 51, 120, 'female', 1.8, 'mg'),
('Vitamin A', 51, 120, 'female', 700, 'µg'),
('Vitamin C', 51, 120, 'female', 75, 'mg'),
('Vitamin D', 51, 120, 'female', 600, 'IU'), -- 800 for 70+
('Vitamin E', 51, 120, 'female', 15, 'mg'),
('Vitamin K', 51, 120, 'female', 90, 'µg'),
('B1 (Thiamine)', 51, 120, 'female', 1.1, 'mg'),
('B2 (Riboflavin)', 51, 120, 'female', 1.1, 'mg'),
('B3 (Niacin)', 51, 120, 'female', 14, 'mg'),
('B5 (Pantothenic Acid)', 51, 120, 'female', 5, 'mg'),
('B6 (Pyridoxine)', 51, 120, 'female', 1.5, 'mg'),
('B7 (Biotin)', 51, 120, 'female', 30, 'µg'),
('B9 (Folate)', 51, 120, 'female', 400, 'µg'),
('B12 (Cobalamin)', 51, 120, 'female', 2.4, 'µg'),
('Choline', 51, 120, 'female', 425, 'mg'),
('Fiber', 51, 120, 'female', 21, 'g');
