-- Enable UUID extension if not already enabled (though we are using text IDs for now to match legacy data)
-- create extension if not exists "uuid-ossp";

-- 1. Recipes Table
create table public.recipes (
  id text primary key,
  title text not null,
  type text not null, -- 'breakfast', 'lunch', 'dinner', 'snack'
  calories integer not null,
  protein integer not null,
  carbs integer not null,
  fat integer not null,
  diet text[] not null default '{}', -- Array of diet types e.g. ['vegan', 'vegetarian']
  image text,
  prep_time integer not null,
  servings integer not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Ingredients Table
create table public.ingredients (
  id bigint generated by default as identity primary key,
  recipe_id text references public.recipes(id) on delete cascade,
  item text not null,
  amount text not null,
  is_miracle_product boolean default false
);

-- 3. Instructions Table
create table public.instructions (
  id bigint generated by default as identity primary key,
  recipe_id text references public.recipes(id) on delete cascade,
  step_text text not null,
  step_order integer not null
);

-- Set up Row Level Security (RLS)
-- For now, we'll allow public read access, but restrict write access to service role (or specific users if authenticated)
alter table public.recipes enable row level security;
alter table public.ingredients enable row level security;
alter table public.instructions enable row level security;

-- Policy to allow anyone to read recipes
create policy "Allow public read access on recipes"
on public.recipes for select
to anon
using (true);

create policy "Allow public read access on ingredients"
on public.ingredients for select
to anon
using (true);

create policy "Allow public read access on instructions"
on public.instructions for select
to anon
using (true);

-- Policy to allow Anon to insert (TEMPORARY FOR SEEDING - DISABLE AFTER SEEDING)
-- Ideally you use the Service Role key for seeding, but for simplicity with the Anon key provided:
create policy "Allow anon insert on recipes"
on public.recipes for insert
to anon
with check (true);

create policy "Allow anon insert on ingredients"
on public.ingredients for insert
to anon
with check (true);

create policy "Allow anon insert on instructions"
on public.instructions for insert
to anon
with check (true);
